### ISSUE TITLE
Toggle enableUnsavedEditIndicator

### ISSUE THREAD

**Issue by Minasmins** [microsoft/FluentUIEditableDetailsList#57]
Hi,

sorry for the noobish question but how do i toggle the UnsavedEditIndiator? In the demo the Icon just becomes gray as soon as you submit the changes but but if im correct i cant see what you are doing to acomplish that :)

I hope you can help me

**Comment by kushalmehrotra713** [comment]
Hi @Minasmins 
The purpose of this indicator is to let the user know that there may be changes on the Grid which the user hasn't Submitted(in case the user has a callback hook to make API calls on 'Submit' button click).

This aligns with the most standard use-case of the Grid where 
1. The user makes a change using Grid's editability features
2. Intends to save the changes in the backend by clicking the 'Submit' button(hooking it to an API call) but is unsure if he/she has already done so or not.

In such a case, the user can see the UnsavedEditIndicator on the Grid. If the indicator is enabled, the user knows that the changes have yet to be submitted. 

This feature also servers another use-case as explained below:-
1) The user makes a bunch of unsaved changes to the Grid data
2) Due to some reason, the user now wants to revert all the changes made after the last submit.
3) The UnsavedEditIndicator will show as enabled as there are unsaved changes.
4) The user can click on 'Reset Data' button on the Command Bar. This reverts all the unsaved changes in the grid to the state after the last 'Submit' action. The UnsavedEditIndicator now shows as disabled, indicating that the changes have been reverted.

**Comment by kushalmehrotra713** [comment]
Hi @Minasmins 
Closing this issue now since I havent heard back on this. Please feel free to open new threads for clarifications.
